language: node_js

node_js:
- '7'

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
  postgres: "9.4"

script:
  npm run coverage

before_install:
  - pip install --user codecov

after_success:
  - codecov --file coverage/lcov.info --disable search

notifications:
  email:
    on_success: never
    on_failure: never
