module.exports = [
  './home',
  './github-login',
  './github-auth',
  './github-star',
  './landing',
  './public',
  './app-twenty',
  './app-pomodoro',
  './app-lpop-admin',
  './app-add',
  './logout',
  './app-lpop-api',
  './app-lpop',
  './app-lpop-servefiles',
  './wifipwd',
].map(require);
